# Generated by Django 3.2.12 on 2022-03-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20220323_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
